name: MyProject

options:
  deploymentTarget:
    iOS: "9.0"
  usesTabs: false
  tabWidth: 2
  indentWidth: 2

targets:
  MyProject:
    type: application
    platform: iOS
    sources: [MyProject, main.jsbundle]
    scheme:
      parallelizeBuild: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.reactjs.native.example.$(PRODUCT_NAME:rfc1034identifier)
        CLANG_ENABLE_MODULES: true
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
          - -lc++
